# Generated by Django 2.2.6 on 2019-10-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ma_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
