# Generated by Django 2.2.6 on 2019-11-26 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ma_app', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
